---
engines:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 200
  eslint:
    enabled: true
    channel: "eslint-3"
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/
- coverage/
- docker/
